name: "Code Checking"

on: [
    push,
    pull_request
]

jobs:
    code-checking-php74:
        name: "Code Checking php7.4"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - name: "Install Php 7.4"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  tools: composer:v2
                  extensions: json, intl
            - name: "Validate composer.json"
              run: php $(which composer) validate --strict
            - name: "Install dependencies with composer"
              run: php $(which composer) install --no-interaction --no-progress
            - name: "Run PHP CodeSniffer"
              run: php vendor/bin/phpcs --standard=phpcs.xml
            - name: "Run PHPStan"
              run: php vendor/bin/phpstan analyse
    code-checking-php81:
        name: "Code Checking php8.1"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - name: "Install Php 8.1"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  tools: composer:v2
                  extensions: json, intl
            - name: "Validate composer.json"
              run: php $(which composer) validate --strict
            - name: "Install dependencies with composer"
              run: php $(which composer) install --no-interaction --no-progress
            - name: "Run PHP CodeSniffer"
              run: php vendor/bin/phpcs --standard=phpcs.xml
            - name: "Run PHPStan"
              run: php vendor/bin/phpstan analyse
    code-checking-php82:
        name: "Code Checking php8.2"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - name: "Install Php 8.2"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: composer:v2
                  extensions: json, intl
            - name: "Validate composer.json"
              run: php $(which composer) validate --strict
            - name: "Install dependencies with composer"
              run: php $(which composer) install --no-interaction --no-progress
            - name: "Run PHP CodeSniffer"
              run: php vendor/bin/phpcs --standard=phpcs.xml
            - name: "Run PHPStan"
              run: php vendor/bin/phpstan analyse
    code-checking-php83:
        name: "Code Checking php8.3"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - name: "Install Php 8.3"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2
                  extensions: json, intl
            - name: "Validate composer.json"
              run: php $(which composer) validate --strict
            - name: "Install dependencies with composer"
              run: php $(which composer) install --no-interaction --no-progress
            - name: "Run PHP CodeSniffer"
              run: php vendor/bin/phpcs --standard=phpcs.xml
            - name: "Run PHPStan"
              run: php vendor/bin/phpstan analyse
